# Generated by Django 3.2.9 on 2021-11-09 13:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('order_number', models.IntegerField()),
            ],
            options={
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('order_number', models.IntegerField()),
                ('progress', models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Completed'), ('R', 'Revisiting')], default='NS', max_length=10)),
            ],
            options={
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('order_number', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='dezignprocess.step')),
            ],
            options={
                'ordering': ['-order_number'],
            },
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
        migrations.AddField(
            model_name='knowledgeresources',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='dezignprocess.step'),
        ),
    ]
