# Generated by Django 3.2.9 on 2021-11-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0002_auto_20211109_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeResources',
            new_name='KnowledgeResource',
        ),
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
        migrations.AlterModelOptions(
            name='knowledgeresource',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['order_number']},
        ),
        migrations.RenameField(
            model_name='knowledgeresource',
            old_name='post',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='post',
            new_name='step',
        ),
    ]
