# Generated by Django 3.2.9 on 2021-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0003_auto_20211109_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='progress',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Revisiting', 'Revisiting')], default='Not Started', max_length=11),
        ),
    ]
