# Generated by Django 3.2.9 on 2021-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0005_alter_step_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeresource',
            name='step',
        ),
        migrations.RemoveField(
            model_name='template',
            name='step',
        ),
        migrations.AddField(
            model_name='step',
            name='resources',
            field=models.ManyToManyField(to='dezignprocess.KnowledgeResource'),
        ),
        migrations.AddField(
            model_name='step',
            name='templates',
            field=models.ManyToManyField(to='dezignprocess.Template'),
        ),
        migrations.AlterField(
            model_name='step',
            name='progress',
            field=models.CharField(choices=[('Not Started', '0'), ('In Progress', '1'), ('Completed', '2'), ('Revisiting', '3')], default='Not Started', max_length=15),
        ),
    ]
