# Generated by Django 3.2.9 on 2021-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0007_auto_20211112_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='list_number',
            field=models.IntegerField(default='1'),
        ),
    ]
