# Generated by Django 3.2.9 on 2021-11-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0008_alter_step_list_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StepTwo',
        ),
    ]
