# Generated by Django 3.2.9 on 2021-11-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_unique',
        ),
    ]
