# Generated by Django 3.2.9 on 2021-11-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezignprocess', '0011_remove_comment_user_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='step',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='dezignprocess_step', to=settings.AUTH_USER_MODEL),
        ),
    ]
