# Generated by Django 3.2.9 on 2021-11-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezignprocess', '0014_alter_comment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='dezign_thinker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='auth.user'),
            preserve_default=False,
        ),
    ]
