# Generated by Django 3.2.9 on 2021-11-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0016_alter_comment_dezign_thinker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dezign_thinker',
        ),
    ]
