# Generated by Django 3.2.9 on 2021-11-16 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezignprocess', '0018_step_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
