# Generated by Django 3.2.9 on 2021-11-17 10:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0019_auto_20211116_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
