# Generated by Django 3.2.9 on 2021-11-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0021_auto_20211118_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='link',
        ),
    ]
