# Generated by Django 3.2.9 on 2021-11-18 20:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0022_remove_step_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeresource',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
