# Generated by Django 3.2.9 on 2021-11-19 10:38

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0024_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='step',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='step',
            name='video_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='step',
            name='video_two',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='step',
            name='videotwo_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RemoveField(
            model_name='step',
            name='resources',
        ),
        migrations.AddField(
            model_name='step',
            name='resources',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KnowledgeResource',
        ),
    ]
