# Generated by Django 3.2.9 on 2021-11-19 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0025_auto_20211119_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='video',
            new_name='video_two_url',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='video_two',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='step',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
