# Generated by Django 3.2.9 on 2021-11-19 12:57

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0027_alter_step_videotwo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='videotwo_name',
            new_name='video_three_name',
        ),
        migrations.AddField(
            model_name='step',
            name='video_three_url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AddField(
            model_name='step',
            name='video_two_name',
            field=models.CharField(default='placeholder', max_length=80),
        ),
        migrations.AlterField(
            model_name='step',
            name='video_name',
            field=models.CharField(default='placeholder', max_length=80),
        ),
    ]
