# Generated by Django 3.2.9 on 2021-11-22 19:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0028_auto_20211119_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='template_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
