# Generated by Django 3.2.9 on 2021-11-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0030_template_slug_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='slug_template',
            new_name='slug',
        ),
    ]
