# Generated by Django 3.2.9 on 2021-11-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0032_auto_20211122_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='step',
        ),
        migrations.AddField(
            model_name='template',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='dezignprocess.step'),
            preserve_default=False,
        ),
    ]
