# Generated by Django 3.2.9 on 2021-12-01 13:49

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0034_alter_template_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='placeholder', max_length=80, unique=True)),
                ('slug', models.SlugField(default='steps_document', max_length=80)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('template_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('order_number', models.IntegerField()),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.RenameField(
            model_name='step',
            old_name='templates',
            new_name='tools',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AddField(
            model_name='tool',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='dezignprocess.step'),
        ),
    ]
