# Generated by Django 3.2.9 on 2021-12-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezignprocess', '0035_auto_20211201_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='progress',
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('progress', models.CharField(choices=[('Not Started', '0'), ('In Progress', '1'), ('Completed', '2'), ('Revisiting', '3')], default='Not Started', max_length=15)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dezignprocess.step')),
                ('username', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_on'],
            },
        ),
    ]
