# Generated by Django 3.2.9 on 2021-12-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0036_auto_20211201_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Revisiting', 'Revisiting')], default='Not Started', max_length=15),
        ),
    ]
