# Generated by Django 3.2.9 on 2021-12-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0037_alter_progress_progress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'get_latest_by': ['-updated_on'], 'ordering': ['-updated_on']},
        ),
        migrations.AlterField(
            model_name='progress',
            name='step',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dezignprocess.step'),
        ),
    ]
