# Generated by Django 3.2.9 on 2021-12-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezignprocess', '0038_auto_20211202_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='username_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='username_step', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dezignprocess.step'),
        ),
    ]
