# Generated by Django 3.2.9 on 2021-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0039_auto_20211202_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='progress_status',
        ),
    ]
