# Generated by Django 3.2.9 on 2021-12-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0040_comment_progress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
