# Generated by Django 3.2.9 on 2021-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0041_step_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'get_latest_by': ['updated_on'], 'ordering': ['updated_on']},
        ),
        migrations.AlterField(
            model_name='progress',
            name='name',
            field=models.CharField(default='username', max_length=80),
        ),
    ]
