# Generated by Django 3.2.9 on 2021-12-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezignprocess', '0044_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'get_latest_by': ['updated_on'], 'ordering': ['updated_on'], 'verbose_name_plural': 'Progress'},
        ),
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
        migrations.RemoveField(
            model_name='step',
            name='resources',
        ),
        migrations.AddField(
            model_name='step',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resource', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='step',
            name='tools',
        ),
        migrations.AddField(
            model_name='step',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='tool', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='dezignprocess.step')),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
