# Generated by Django 3.2.9 on 2021-12-15 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0045_auto_20211215_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='step',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='step',
        ),
        migrations.AddField(
            model_name='resource',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='step',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resource', to='dezignprocess.Resource'),
        ),
        migrations.AlterField(
            model_name='step',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='tool', to='dezignprocess.Tool'),
        ),
    ]
