# Generated by Django 3.2.9 on 2021-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0046_auto_20211215_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['order_number'], 'verbose_name_plural': 'Resources'},
        ),
        migrations.AddField(
            model_name='resource',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
