# Generated by Django 3.2.9 on 2021-12-15 15:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0049_auto_20211215_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='step',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='1', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='1', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='template_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
