# Generated by Django 3.2.9 on 2021-12-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0050_auto_20211215_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='step',
            name='step_image',
        ),
        migrations.AddField(
            model_name='step',
            name='feature_image',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='featured_image', to='dezignprocess.images'),
        ),
        migrations.AddField(
            model_name='step',
            name='steps_image',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='step_image', to='dezignprocess.images'),
        ),
    ]
