# Generated by Django 3.2.9 on 2021-12-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0051_auto_20211215_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='video_name',
        ),
        migrations.RemoveField(
            model_name='step',
            name='video_three_name',
        ),
        migrations.RemoveField(
            model_name='step',
            name='video_three_url',
        ),
        migrations.RemoveField(
            model_name='step',
            name='video_two_name',
        ),
        migrations.RemoveField(
            model_name='step',
            name='video_two_url',
        ),
        migrations.RemoveField(
            model_name='step',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='template_image',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tool_image', to='dezignprocess.images'),
        ),
    ]
