# Generated by Django 3.2.9 on 2021-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0052_auto_20211215_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'get_latest_by': ['added'], 'ordering': ['order_number'], 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='images',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
