# Generated by Django 3.2.9 on 2021-12-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0053_auto_20211215_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='username_id',
        ),
    ]
