# Generated by Django 3.2.9 on 2021-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0054_remove_step_username_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_name',
            field=models.CharField(blank=True, default='placeholder', max_length=100),
        ),
    ]
