# Generated by Django 3.2.9 on 2021-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0057_auto_20211223_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='deletable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='list_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='deletable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='steps_document', max_length=80),
        ),
        migrations.AlterField(
            model_name='tool',
            name='title',
            field=models.CharField(default='placeholder', max_length=80, unique=True),
        ),
    ]
