# Generated by Django 3.2.9 on 2021-12-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignprocess', '0058_auto_20211223_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deletable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
