# Generated by Django 3.2.9 on 2021-11-22 18:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezignsurvey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='title',
            new_name='survey_title',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
