# Generated by Django 3.2.9 on 2021-11-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0002_auto_20211129_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultquestions',
            name='age_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.agerange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultquestions',
            name='gender',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultquestions',
            name='industry',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultquestions',
            name='job_title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultquestions',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
