# Generated by Django 3.2.9 on 2021-11-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0003_auto_20211129_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultquestions',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultquestions_set', to='dezigntools.survey'),
        ),
    ]
