# Generated by Django 3.2.9 on 2021-11-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0004_alter_defaultquestions_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultquestions',
            name='age_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.agerange'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.gender'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='industry',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='job_title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
