# Generated by Django 3.2.9 on 2021-11-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0005_auto_20211129_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='include_default_questions',
        ),
    ]
