# Generated by Django 3.2.9 on 2021-12-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0007_auto_20211210_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultquestions',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
