# Generated by Django 3.2.9 on 2021-12-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0008_defaultquestions_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('age_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.agerange')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='DefaultQuestions',
        ),
        migrations.AddField(
            model_name='defaultquestion',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='dezigntools.industry'),
        ),
        migrations.AddField(
            model_name='defaultquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaultquestions_set', to='dezigntools.survey'),
        ),
    ]
