# Generated by Django 3.2.9 on 2021-12-12 01:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0010_auto_20211212_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='SurveyImage',
        ),
    ]
