# Generated by Django 3.2.9 on 2021-12-15 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0013_alter_survey_survey_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agerange',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='defaultquestion',
            name='age_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='age_range_set', to='dezigntools.agerange'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaultquestion',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gender_set', to='dezigntools.gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaultquestion',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industry_set', to='dezigntools.industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='industry',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
