# Generated by Django 3.2.9 on 2021-12-19 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0014_auto_20211215_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='l99appihvpsotfmk575l', max_length=255, null=True, verbose_name='image'),
        ),
    ]
