# Generated by Django 3.2.9 on 2021-12-19 16:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0015_alter_survey_survey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agerange',
            name='do_not_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='do_not_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='do_not_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='do_not_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=' efeeyko4svga74cweezl', max_length=255, null=True, verbose_name='image'),
        ),
    ]
