# Generated by Django 3.2.9 on 2021-12-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0016_auto_20211219_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='do_not_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultquestion',
            name='do_not_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='do_not_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='do_not_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='do_not_delete',
            field=models.BooleanField(default=False),
        ),
    ]
