# Generated by Django 3.2.9 on 2021-12-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0018_alter_survey_survey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='age_range',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dezigntools.agerange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dezigntools.gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dezigntools.industry'),
            preserve_default=False,
        ),
    ]
