# Generated by Django 3.2.9 on 2021-12-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0019_auto_20211220_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultQuestion',
        ),
    ]
