# Generated by Django 3.2.9 on 2021-12-21 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0020_delete_defaultquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_question', models.CharField(max_length=128)),
                ('do_not_delete', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.survey')),
            ],
        ),
        migrations.CreateModel(
            name='GenderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_question', models.CharField(max_length=128)),
                ('do_not_delete', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.survey')),
            ],
        ),
        migrations.CreateModel(
            name='AgeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_question', models.CharField(max_length=128)),
                ('do_not_delete', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.survey')),
            ],
        ),
    ]
