# Generated by Django 3.2.9 on 2021-12-21 02:14

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0022_auto_20211221_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.industryquestion'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='jevm2uwqm08nn5rmfmdq', max_length=255, null=True, verbose_name='image'),
        ),
    ]
