# Generated by Django 3.2.9 on 2021-12-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0023_auto_20211221_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['title'], 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterField(
            model_name='agequestion',
            name='age_question',
            field=models.CharField(default='Please select your age range:', max_length=128),
        ),
        migrations.AlterField(
            model_name='genderquestion',
            name='gender_question',
            field=models.CharField(default='Please select your preferred gender:', max_length=128),
        ),
        migrations.AlterField(
            model_name='industryquestion',
            name='industry_question',
            field=models.CharField(default='Please select your Industry of employment:', max_length=128),
        ),
    ]
