# Generated by Django 3.2.9 on 2021-12-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0024_auto_20211221_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agequestion',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='genderquestion',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='industryquestion',
            name='survey',
        ),
        migrations.CreateModel(
            name='DefaultQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_not_delete', models.BooleanField(default=False)),
                ('age_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.agequestion')),
                ('gender_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.genderquestion')),
                ('industry_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.industryquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.survey')),
            ],
            options={
                'verbose_name_plural': 'Default Questions',
                'ordering': ['survey'],
            },
        ),
    ]
