# Generated by Django 3.2.9 on 2021-12-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0025_auto_20211221_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agerange',
            name='age_question',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='gender_question',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='industry_question',
        ),
        migrations.AddField(
            model_name='defaultquestions',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='age_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agequestion_set', to='dezigntools.agequestion'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='gender_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genderquestion_set', to='dezigntools.genderquestion'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='industry_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industryquestion_set', to='dezigntools.industryquestion'),
        ),
        migrations.CreateModel(
            name='DefaultOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_not_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('age_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_age_question', to='dezigntools.defaultquestions')),
                ('age_ranges', models.ManyToManyField(related_name='age_ranges_set', to='dezigntools.AgeRange')),
                ('gender_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_gender_question', to='dezigntools.defaultquestions')),
                ('genders', models.ManyToManyField(related_name='genders_set', to='dezigntools.Gender')),
                ('industries', models.ManyToManyField(related_name='industries_set', to='dezigntools.Industry')),
                ('industry_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_industry_question', to='dezigntools.defaultquestions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.survey')),
            ],
            options={
                'verbose_name_plural': 'Default Questions',
                'ordering': ['survey'],
            },
        ),
    ]
