# Generated by Django 3.2.9 on 2021-12-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0026_auto_20211221_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultoptions',
            options={'ordering': ['survey'], 'verbose_name_plural': 'Default Options'},
        ),
    ]
