# Generated by Django 3.2.9 on 2021-12-21 14:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0027_alter_defaultoptions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultoptions',
            name='age_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agequestion_set', to='dezigntools.agequestion'),
        ),
        migrations.AlterField(
            model_name='defaultoptions',
            name='gender_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genderquestion_set', to='dezigntools.genderquestion'),
        ),
        migrations.AlterField(
            model_name='defaultoptions',
            name='industry_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industryquestion_set', to='dezigntools.industryquestion'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='age_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_question_set', to='dezigntools.agequestion'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='gender_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gende_question_set', to='dezigntools.genderquestion'),
        ),
        migrations.AlterField(
            model_name='defaultquestions',
            name='industry_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_question_set', to='dezigntools.industryquestion'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='son8liypgdn9yzc3lx7h', max_length=255, null=True, verbose_name='image'),
        ),
    ]
