# Generated by Django 3.2.9 on 2021-12-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0028_auto_20211221_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultQuestions',
        ),
    ]
