# Generated by Django 3.2.9 on 2021-12-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0029_delete_defaultquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.ManyToManyField(related_name='question_age_ranges_set', to='dezigntools.DefaultOptions')),
                ('gender', models.ManyToManyField(related_name='question_genders_set', to='dezigntools.DefaultOptions')),
                ('industry', models.ManyToManyField(related_name='question_industries_set', to='dezigntools.DefaultOptions')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dezigntools.submission')),
            ],
            options={
                'verbose_name_plural': 'Default Answers',
                'ordering': ['submission'],
            },
        ),
    ]
