# Generated by Django 3.2.9 on 2021-12-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0030_defaultanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='industry',
        ),
    ]
