# Generated by Django 3.2.9 on 2021-12-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0031_auto_20211221_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='age_range',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_age_ranges_set', to='dezigntools.defaultoptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_genders_set', to='dezigntools.defaultoptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='industry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_industries_set', to='dezigntools.defaultoptions'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='defaultanswers',
            name='age_range',
        ),
        migrations.AddField(
            model_name='defaultanswers',
            name='age_range',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions_age_ranges_set', to='dezigntools.defaultoptions'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='defaultanswers',
            name='gender',
        ),
        migrations.AddField(
            model_name='defaultanswers',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions_genders_set', to='dezigntools.defaultoptions'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='defaultanswers',
            name='industry',
        ),
        migrations.AddField(
            model_name='defaultanswers',
            name='industry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions_industries_set', to='dezigntools.defaultoptions'),
            preserve_default=False,
        ),
    ]
