# Generated by Django 3.2.9 on 2021-12-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0032_auto_20211221_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultoptions',
            old_name='is_active',
            new_name='active',
        ),
    ]
