# Generated by Django 3.2.9 on 2021-12-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0033_rename_is_active_defaultoptions_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='industry',
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='age_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_age_ranges_set', to='dezigntools.agerange'),
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_genders_set', to='dezigntools.gender'),
        ),
        migrations.AlterField(
            model_name='defaultanswers',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_industries_set', to='dezigntools.industry'),
        ),
    ]
