# Generated by Django 3.2.9 on 2021-12-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0034_auto_20211221_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultanswers',
            name='survey',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='dezigntools.survey'),
            preserve_default=False,
        ),
    ]
