# Generated by Django 3.2.9 on 2021-12-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dezigntools', '0039_auto_20211227_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultanswers',
            options={'ordering': ['submission'], 'verbose_name_plural': 'Default Answers'},
        ),
        migrations.AddField(
            model_name='defaultanswers',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dezigntools.submission'),
            preserve_default=False,
        ),
    ]
