# Generated by Django 3.2.9 on 2021-12-11 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'get_latest_by': ['updated_on'], 'ordering': ['updated_on']},
        ),
        migrations.AddField(
            model_name='verification',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
