# Generated by Django 3.2.9 on 2021-12-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211211_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
