# Generated by Django 3.2.9 on 2021-12-15 10:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
